#!/usr/bin/env bash
#
# Creates symbolic links to all the specified files in the $HOME directory

DOTFILES_DIR=$HOME/.dotfiles

echo "Setting up symlinks"

ln -fs "$DOTFILES_DIR/zsh/.zshrc.symlink" "$HOME/.zshrc"
ln -fs "$DOTFILES_DIR/git/.gitconfig.symlink" "$HOME/.gitconfig"
ln -fs "$DOTFILES_DIR/git/.gitmessage.symlink" "$HOME/.gitmessage"
ln -fs "$DOTFILES_DIR/git/.gitignore.symlink" "$HOME/.gitignore"

echo "Done"
