#!/usr/bin/env bash
#
# Creates symbolic links to all the specified files in the $HOME directory

DOTFILES_ROOT="$HOME/.dotfiles"

echo "Setting up symlinks"

ln -fs "$DOTFILES_ROOT/zsh/.zshrc.symlink" "$HOME/.zshrc"
ln -fs "$DOTFILES_ROOT/git/.gitconfig.symlink" "$HOME/.gitconfig"
ln -fs "$DOTFILES_ROOT/git/.gitmessage.symlink" "$HOME/.gitmessage"
ln -fs "$DOTFILES_ROOT/git/.gitignore.symlink" "$HOME/.gitignore"

echo "Done"
